# Generated by Django 2.2.4 on 2019-08-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CISCO_DNAC_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnaccontrollers',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
