# Generated by Django 2.2.4 on 2019-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CISCO_DNAC_APP', '0002_auto_20190823_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=50, unique=True)),
                ('source_ip', models.GenericIPAddressField()),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('actual_service_id', models.CharField(max_length=50)),
                ('issue_description', models.CharField(blank=True, default='', max_length=100, verbose_name='Issue Description')),
            ],
        ),
    ]
