# Generated by Django 2.2.4 on 2019-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CISCO_DNAC_APP', '0003_webhookevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhookevents',
            old_name='timestamp',
            new_name='Date',
        ),
    ]
